## 入门
### 张量

In [7]:
import torch

In [8]:
x = torch.empty(5, 3)
print(x)

tensor([[2.4156e+36, 4.5695e-41, 2.4156e+36],
        [4.5695e-41, 1.3068e+34, 4.5695e-41],
        [3.5122e+36, 4.5695e-41, 1.4013e-45],
        [4.5695e-41, 0.0000e+00, 0.0000e+00],
        [1.6023e+19, 4.5695e-41, 0.0000e+00]])


In [9]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8931, 0.4181, 0.3714],
        [0.3106, 0.0399, 0.0709],
        [0.4508, 0.3512, 0.0579],
        [0.3971, 0.2662, 0.3176],
        [0.0681, 0.3924, 0.7676]])


In [11]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1555,  0.4774,  0.4219],
        [ 0.1302,  1.0446, -0.2604],
        [ 1.1210, -0.8085, -0.6131],
        [ 1.2876, -0.0795,  1.5187],
        [ 1.5708,  0.4301, -1.4819]])


In [14]:
print(x.size())

torch.Size([5, 3])


### 运算

In [15]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.8640,  0.4795,  1.3846],
        [ 0.8731,  1.5899, -0.0630],
        [ 1.7486, -0.1590,  0.0648],
        [ 2.1405,  0.7954,  1.5703],
        [ 1.8081,  0.8071, -0.4912]])


In [16]:
print(torch.add(x,y))

tensor([[ 1.8640,  0.4795,  1.3846],
        [ 0.8731,  1.5899, -0.0630],
        [ 1.7486, -0.1590,  0.0648],
        [ 2.1405,  0.7954,  1.5703],
        [ 1.8081,  0.8071, -0.4912]])


In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.8640,  0.4795,  1.3846],
        [ 0.8731,  1.5899, -0.0630],
        [ 1.7486, -0.1590,  0.0648],
        [ 2.1405,  0.7954,  1.5703],
        [ 1.8081,  0.8071, -0.4912]])


In [18]:
y.add_(x)
print(y)

tensor([[ 1.8640,  0.4795,  1.3846],
        [ 0.8731,  1.5899, -0.0630],
        [ 1.7486, -0.1590,  0.0648],
        [ 2.1405,  0.7954,  1.5703],
        [ 1.8081,  0.8071, -0.4912]])


In [19]:
print(x[:, 1])

tensor([ 0.4774,  1.0446, -0.8085, -0.0795,  0.4301])


In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.3372])
-1.3372260332107544


## Numpy桥

### 将torch的Tensor转化为NumPy数组

In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 将NumPy数组转化为Torch张量

In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA上的张量

In [28]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([-0.3372], device='cuda:0')
tensor([-0.3372], dtype=torch.float64)
